### ISSUE TITLE
Getting ClassNotFoundException for net.bytebuddy.jar.asm.commons.SignatureRemapper since 1.8.11

### ISSUE THREAD

**Issue by florimon** [raphw/byte-buddy#526]
Hi,
On the http://bytebuddy.net/#/tutorial page, the code under the section "Reloading a class" does not work on byte buddy versions >= 1.8.11. The error is:

```
java.lang.NoClassDefFoundError: net/bytebuddy/jar/asm/commons/SignatureRemapper
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.writeTo(TypeWriter.java:2910)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2883)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1652)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:180)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:94)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2669)
	at nl.ing.insurance.tests.config.ByteBuddyTest.testIt(ByteBuddyTest.java:32)
	...
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.jar.asm.commons.SignatureRemapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

The testcode is:

```
public class ByteBuddyTest {

    static class Foo {
        String m() { return "foo"; }
    }

    static class Bar {
        String m() { return "bar"; }
    }

    @Test
    public void testIt() {
        ByteBuddyAgent.install();
        Foo foo = new Foo();
        new ByteBuddy()
                .redefine(Bar.class)
                .name(Foo.class.getName())
                .make()
                .load(Foo.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
        assertThat(foo.m(), is("bar"));
    }
}
```

All versions <= 1.8.10 work just fine.

**Comment by raphw** [comment]
I messed up the shading, I had to trim it to get the module-info to work on another branch and did not realize I was missing a class. Fixed on master.
