### ISSUE TITLE
ByteBuddy 1.11.17 does not work with Mockito 3.12.4

### ISSUE THREAD

**Issue by vyazelenko** [raphw/byte-buddy#1116]
Not sure if this issue should be reported against Mockito instead but when I've tried to upgrade [Aeron](https://github.com/real-logic/aeron) to ByteBuddy 1.11.17 I got the following exception from multiple tests:
```java
java.lang.NoSuchMethodError: net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler.compile(Lnet/bytebuddy/description/type/TypeDescription;)Lnet/bytebuddy/dynamic/scaffold/MethodGraph$Linked;
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isOverridden(MockMethodAdvice.java:209)
	at java.io.PrintStream.println(PrintStream.java:805)
...
```

**Comment by raphw** [comment]
Darn, seems like I got a source compatible change in there that's not binary compatible. I had a plugin in place to avoid such breakage but it seems that this did not catch the issue.

I think the easiest is to upgrade Mockito to the new version. Maybe I need to reintroduce some methods to avoid the breakage, toom

**Comment by raphw** [comment]
Just released 1.11.18 which should avoid this issue. Thanks for the quick feedback.

**Comment by vyazelenko** [comment]
@vyazelenko Thanks for the prompt fix. I can confirm that 1.11.18 works as expected.
